name: Test Two

on:
  workflow_dispatch:
  workflow_call:

env:
  NOX_VERSION: "2022.8.7"
  COLUMNS: 160
  AWS_MAX_ATTEMPTS: "10"
  AWS_RETRY_MODE: "adaptive"

jobs:

  step_one:
    name: Step One 
    runs-on: ubuntu-latest
    steps:
      - name: Echo Step
        run: echo "Test Two Step One"

  step_two:
    name: Step Two
    runs-on: ubuntu-latest
    needs:
      - step_one
    steps:
      - name: Echo Step
        run: echo "Test Two Step Two"

  step_three:
    name: Step Three
    runs-on: ubuntu-latest
    needs:
      - step_one
      - step_two
    steps:
      - name: Echo Step
        run: echo "Test Two Step Three"

  step_four:
    name: Step Four
    needs:
      - step_one
      - step_two
      - step_three
    uses: garethgreenaway/salt/.github/workflows/test-three.yml@hotfix/salt-pkg-tests
