name: Test Package Download and Install

on:
  push: {}
  pull_request: {}
  workflow_dispatch:
    inputs:
      salt-version:
        type: string
        default: ""
        description: >
          The Salt version to set prior to running tests or building packages.
          If not set, it is discover at run time, like, for example, capturing
          the output of running `python3 salt/version.py`
      testrun-type:
        description: Type of test run
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - changed

env:
  NOX_VERSION: "2022.8.7"
  COLUMNS: 160
  AWS_MAX_ATTEMPTS: "10"
  AWS_RETRY_MODE: "adaptive"

jobs:

  generate-matrix:
    name: Generate Test Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-include: ${{ steps.generate-matrix.outputs.matrix }}
      transport-matrix-include: ${{ steps.generate-transport-matrix.outputs.matrix }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

  dependencies:
    name: Setup Test Dependencies
    needs:
      - generate-matrix
    runs-on:
      - self-hosted
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Define Nox Session
        run: |
          if [ "${{ matrix.transport }}" != "tcp" ]; then
            echo NOX_SESSION=${{ inputs.nox-session }} >> "$GITHUB_ENV"
          else
            echo NOX_SESSION=${{ inputs.nox-session }}-tcp >> "$GITHUB_ENV"
          fi

  test:
    name: Test
    runs-on:
      - self-hosted
    timeout-minutes: 240  # 4 Hours - More than this and something is wrong
    needs:
      - dependencies
      - generate-matrix
    strategy:
      fail-fast: false

    steps:
      - name: Define Nox Session
        run: |
          if [ "${{ matrix.transport }}" != "tcp" ]; then
            echo NOX_SESSION=${{ inputs.nox-session }} >> "$GITHUB_ENV"
          else
            echo NOX_SESSION=${{ inputs.nox-session }}-tcp >> "$GITHUB_ENV"
          fi

      - name: Run Package Download and Install Tests
        if: always()
        continue-on-error: true
        run: |
          nox --force-color -- --run-slow --package-tests

      - name: Set Exit Status
        if: always()
        run: |
          python3 -c "import os; os.makedirs('exitstatus', exist_ok=True)"
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ inputs.distro-slug }}-${{ env.NOX_SESSION }}-${{ matrix.tests-chunk }}-tests

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
